import type { Metadata } from "next"
import { Geist, Geist_Mono, Abril_Fatface } from "next/font/google"
import "./globals.css"
import { ClerkProvider } from "@clerk/nextjs"
import { ThemeProvider } from "@/components/ThemeProvider"
import Navbar from "@/components/navbar/Navbar"
import Container from "@/components/global/Container"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const fatFace = Abril_Fatface({
  weight: "400",
  variable: "--font-abril-fatface",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Socially App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      suppressHydrationWarning
      lang='en'
      className={`${geistSans.className} h-full antialiased`}
    >
      <body className='min-h-full flex flex-col'>
        <ClerkProvider>
          <ThemeProvider
            attribute='class'
            defaultTheme='system'
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            <main className='py-8'>
              <Container>
                <div className='grid grid-cols-1 lg:grid-cols-12 gap-6'>
                  <div className='hidden lg:block lg:col-span-3'>sidebar</div>
                  <div className='lg:col-span-9'>{children}</div>
                </div>
              </Container>
            </main>
          </ThemeProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}
